// Generated by gencpp from file motor_control/MotorCommands.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_MOTORCOMMANDS_H
#define MOTOR_CONTROL_MESSAGE_MOTORCOMMANDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <motor_control/MotorCommand.h>

namespace motor_control
{
template <class ContainerAllocator>
struct MotorCommands_
{
  typedef MotorCommands_<ContainerAllocator> Type;

  MotorCommands_()
    : motorcommands()  {
    }
  MotorCommands_(const ContainerAllocator& _alloc)
    : motorcommands(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::motor_control::MotorCommand_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::motor_control::MotorCommand_<ContainerAllocator> >> _motorcommands_type;
  _motorcommands_type motorcommands;





  typedef boost::shared_ptr< ::motor_control::MotorCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::MotorCommands_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommands_

typedef ::motor_control::MotorCommands_<std::allocator<void> > MotorCommands;

typedef boost::shared_ptr< ::motor_control::MotorCommands > MotorCommandsPtr;
typedef boost::shared_ptr< ::motor_control::MotorCommands const> MotorCommandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::MotorCommands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::MotorCommands_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control::MotorCommands_<ContainerAllocator1> & lhs, const ::motor_control::MotorCommands_<ContainerAllocator2> & rhs)
{
  return lhs.motorcommands == rhs.motorcommands;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control::MotorCommands_<ContainerAllocator1> & lhs, const ::motor_control::MotorCommands_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_control::MotorCommands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::MotorCommands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::MotorCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::MotorCommands_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::MotorCommands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::MotorCommands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2edb3d2f4d8f2a09fe7cbec56216411";
  }

  static const char* value(const ::motor_control::MotorCommands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2edb3d2f4d8f2a0ULL;
  static const uint64_t static_value2 = 0x9fe7cbec56216411ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/MotorCommands";
  }

  static const char* value(const ::motor_control::MotorCommands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::MotorCommands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MotorCommand[] motorcommands\n"
"\n"
"================================================================================\n"
"MSG: motor_control/MotorCommand\n"
"char channel\n"
"float32 angle\n"
;
  }

  static const char* value(const ::motor_control::MotorCommands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::MotorCommands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorcommands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::MotorCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::MotorCommands_<ContainerAllocator>& v)
  {
    s << indent << "motorcommands[]" << std::endl;
    for (size_t i = 0; i < v.motorcommands.size(); ++i)
    {
      s << indent << "  motorcommands[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::motor_control::MotorCommand_<ContainerAllocator> >::stream(s, indent + "    ", v.motorcommands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_MOTORCOMMANDS_H
