// Generated by gencpp from file motor_control/MotorCommand.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_MOTORCOMMAND_H
#define MOTOR_CONTROL_MESSAGE_MOTORCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control
{
template <class ContainerAllocator>
struct MotorCommand_
{
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
    : channel(0)
    , angle(0.0)  {
    }
  MotorCommand_(const ContainerAllocator& _alloc)
    : channel(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _channel_type;
  _channel_type channel;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::motor_control::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::MotorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommand_

typedef ::motor_control::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::motor_control::MotorCommand > MotorCommandPtr;
typedef boost::shared_ptr< ::motor_control::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::MotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control::MotorCommand_<ContainerAllocator1> & lhs, const ::motor_control::MotorCommand_<ContainerAllocator2> & rhs)
{
  return lhs.channel == rhs.channel &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control::MotorCommand_<ContainerAllocator1> & lhs, const ::motor_control::MotorCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_control::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db68853cfad241b5e822c1fa82650502";
  }

  static const char* value(const ::motor_control::MotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb68853cfad241b5ULL;
  static const uint64_t static_value2 = 0xe822c1fa82650502ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/MotorCommand";
  }

  static const char* value(const ::motor_control::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char channel\n"
"float32 angle\n"
;
  }

  static const char* value(const ::motor_control::MotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::MotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::MotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.channel);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_MOTORCOMMAND_H
