// Generated by gencpp from file intera_core_msgs/IOComponentConfiguration.msg
// DO NOT EDIT!


#ifndef INTERA_CORE_MSGS_MESSAGE_IOCOMPONENTCONFIGURATION_H
#define INTERA_CORE_MSGS_MESSAGE_IOCOMPONENTCONFIGURATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intera_core_msgs
{
template <class ContainerAllocator>
struct IOComponentConfiguration_
{
  typedef IOComponentConfiguration_<ContainerAllocator> Type;

  IOComponentConfiguration_()
    : name()
    , config()  {
    }
  IOComponentConfiguration_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , config(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _config_type;
  _config_type config;





  typedef boost::shared_ptr< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> const> ConstPtr;

}; // struct IOComponentConfiguration_

typedef ::intera_core_msgs::IOComponentConfiguration_<std::allocator<void> > IOComponentConfiguration;

typedef boost::shared_ptr< ::intera_core_msgs::IOComponentConfiguration > IOComponentConfigurationPtr;
typedef boost::shared_ptr< ::intera_core_msgs::IOComponentConfiguration const> IOComponentConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator1> & lhs, const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.config == rhs.config;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator1> & lhs, const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace intera_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb7717d13a521b51b5c0a02d493c42fd";
  }

  static const char* value(const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb7717d13a521b51ULL;
  static const uint64_t static_value2 = 0xb5c0a02d493c42fdULL;
};

template<class ContainerAllocator>
struct DataType< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intera_core_msgs/IOComponentConfiguration";
  }

  static const char* value(const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## IO Component configuration data\n"
"string name                           # component name\n"
"string config                         # component configuration JSON\n"
;
  }

  static const char* value(const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.config);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IOComponentConfiguration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intera_core_msgs::IOComponentConfiguration_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "config: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.config);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERA_CORE_MSGS_MESSAGE_IOCOMPONENTCONFIGURATION_H
