// Generated by gencpp from file intera_core_msgs/IOComponentStatus.msg
// DO NOT EDIT!


#ifndef INTERA_CORE_MSGS_MESSAGE_IOCOMPONENTSTATUS_H
#define INTERA_CORE_MSGS_MESSAGE_IOCOMPONENTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <intera_core_msgs/IOStatus.h>

namespace intera_core_msgs
{
template <class ContainerAllocator>
struct IOComponentStatus_
{
  typedef IOComponentStatus_<ContainerAllocator> Type;

  IOComponentStatus_()
    : name()
    , status()  {
    }
  IOComponentStatus_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::intera_core_msgs::IOStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> const> ConstPtr;

}; // struct IOComponentStatus_

typedef ::intera_core_msgs::IOComponentStatus_<std::allocator<void> > IOComponentStatus;

typedef boost::shared_ptr< ::intera_core_msgs::IOComponentStatus > IOComponentStatusPtr;
typedef boost::shared_ptr< ::intera_core_msgs::IOComponentStatus const> IOComponentStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator1> & lhs, const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator1> & lhs, const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace intera_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7daed407477edd76573df598b0375a48";
  }

  static const char* value(const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7daed407477edd76ULL;
  static const uint64_t static_value2 = 0x573df598b0375a48ULL;
};

template<class ContainerAllocator>
struct DataType< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intera_core_msgs/IOComponentStatus";
  }

  static const char* value(const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## IO Component status data\n"
"string name            # component name\n"
"IOStatus status        # component status\n"
"#\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: intera_core_msgs/IOStatus\n"
"## IO status data\n"
"#\n"
"string tag             # one of the values listed below\n"
"#   down     Inoperative, not fully instantiated\n"
"#   ready    OK, fully operational\n"
"#   busy     OK, not ready to output data; input data value may be stale\n"
"#   unready  OK, not operational; data is invalid\n"
"#   error    Error, not operational\n"
"string DOWN      = down\n"
"string READY     = ready\n"
"string BUSY      = busy\n"
"string UNREADY   = unready\n"
"string ERROR     = error\n"
"#\n"
"string id             # message id, for internationalization\n"
"#\n"
"string detail         # optional additional status detail\n"
"#\n"
;
  }

  static const char* value(const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IOComponentStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intera_core_msgs::IOComponentStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intera_core_msgs::IOComponentStatus_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::intera_core_msgs::IOStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERA_CORE_MSGS_MESSAGE_IOCOMPONENTSTATUS_H
