// Generated by gencpp from file pot_control/PotValue.msg
// DO NOT EDIT!


#ifndef POT_CONTROL_MESSAGE_POTVALUE_H
#define POT_CONTROL_MESSAGE_POTVALUE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pot_control
{
template <class ContainerAllocator>
struct PotValue_
{
  typedef PotValue_<ContainerAllocator> Type;

  PotValue_()
    : values()  {
      values.assign(0.0);
  }
  PotValue_(const ContainerAllocator& _alloc)
    : values()  {
  (void)_alloc;
      values.assign(0.0);
  }



   typedef boost::array<float, 2>  _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::pot_control::PotValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pot_control::PotValue_<ContainerAllocator> const> ConstPtr;

}; // struct PotValue_

typedef ::pot_control::PotValue_<std::allocator<void> > PotValue;

typedef boost::shared_ptr< ::pot_control::PotValue > PotValuePtr;
typedef boost::shared_ptr< ::pot_control::PotValue const> PotValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pot_control::PotValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pot_control::PotValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pot_control::PotValue_<ContainerAllocator1> & lhs, const ::pot_control::PotValue_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pot_control::PotValue_<ContainerAllocator1> & lhs, const ::pot_control::PotValue_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pot_control::PotValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pot_control::PotValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pot_control::PotValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pot_control::PotValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pot_control::PotValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pot_control::PotValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pot_control::PotValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c334281ada2d017b8a6955b9529fd69a";
  }

  static const char* value(const ::pot_control::PotValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc334281ada2d017bULL;
  static const uint64_t static_value2 = 0x8a6955b9529fd69aULL;
};

template<class ContainerAllocator>
struct DataType< ::pot_control::PotValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pot_control/PotValue";
  }

  static const char* value(const ::pot_control::PotValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pot_control::PotValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[2] values\n"
;
  }

  static const char* value(const ::pot_control::PotValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pot_control::PotValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PotValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pot_control::PotValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pot_control::PotValue_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POT_CONTROL_MESSAGE_POTVALUE_H
